project:
  type: book

book:
  title: "Recipes"
  author: "Anya Ferguson"
  date: "27/05/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - biscuits.qmd
    - references.qmd

bibliography: references.bib

execute: 
  eval: true
  echo: false
  warning: false

format:
  html:
    theme: cosmo



