project:
  type: book

book:
  title: "Recipes"
  author: "Anya Ferguson"
  date: today
  chapters:
    - index.qmd
    - tips-and-tricks.qmd
    - bread.qmd
    - biscuits.qmd
    - cakes.qmd
    - desserts.qmd
    - dinners.qmd
    - extras.qmd
    - muffins-and-cupcakes.qmd
    - pancakes-and-scones.qmd
    - pastries.qmd
    - traybakes.qmd
    - other.qmd
  repo-url: https://github.com/AnyaJade/recipes
  repo-branch: main

execute: 
  eval: true
  echo: false
  warning: false

format:
  html:
    theme: 
      dark: darkly
      light: cosmo



