project:
  type: book

book:
  title: "Recipes"
  author: "Anya Ferguson"
  date: "`r Sys.Date()`"
  chapters:
    - index.qmd
    - bread.qmd
    - biscuits.qmd
    - cakes.qmd
    - desserts.qmd
    - extras.qmd
    - muffins-and-cupcakes.qmd
    - pancakes-and-scones.qmd
    - pastries.qmd
    - traybakes.qmd
    - other.qmd

execute: 
  eval: true
  echo: false
  warning: false

format:
  html:
    theme: cosmo



