## Tips and Tricks

## Conversions

| Ingredient    | Substitution                            | Notes                                          |
|----------------|--------------------------|------------------------------|
| 100g SR flour | little less than 100g P flour + 1tsp BP | Mix well                                       |
| 1 egg         | 1/4 cup or 2.5oz apple sauce            | Works in fruity, heavy cakes like carrot cake. |
| 1 egg white   | 50ml aquafaba                           | Whips to stiff peaks. Used in mini rolls.      |

## Useful Measurements

1tbsp syrup = 21g \
1tbsp cocoa powder = 10g

| Utensil                   | g   | oz   |
|---------------------------|-----|------|
| Big plastic bowl          | 217 | 7.6  |
| Small glass bowl          | 526 | 18.6 |
| Silver scale dish         | 136 | 4.8  |
| Big sieve                 | 145 | 5.1  |
| Small sieve               | 119 | 4.2  |
| Plastic measuring jug     | 48  | 1.7  |
| Large glass measuring jug | 522 | 18.4 |

## Brownie method {#sec-brownie-method}

Makes thick gloopy batter and nice gooey brownies.

-   Melt chocolate and butter slowly.
-   Stir in sugar and set aside.
-   Beat eggs in small jug with fork.
-   Well method to combine everything, just before going in the oven.

## Aquafaba {#sec-aquafaba}

- Whip on speed 4.
- 4-5 mins for light and fluffy.
- 8 mins for stiff peaks?

## Sterilising jars {#sec-jars}

- Wash glass in hot soapy water, rinse well.
- Bake in oven rim side up on baking tray at 100° for 30mins.
- Boil metal lids in water for 10mins.

## Other notes {#sec-other}

-   When using apple cider vinegar and BP in vegan cakes, once mixed get in oven quickly.
-   Chocolate chips work better than cut up chocolate in cookies (because the way they melt?).
