
```{r}
title <- stringr::str_to_title(get_part_of_recipe(recipes, id_number, "name"))
```

```{r}
#| output: asis

vegan <- get_part_of_recipe(recipes, id_number, "vegan")

vegan <- ifelse(is.na(vegan), "", "{{< fa leaf size=2xs >}}")

freezes <- get_part_of_recipe(recipes, id_number, "freezes")

freezes <- ifelse(is.na(freezes), "", "{{< fa snowflake size=2xs >}}")

family <- get_part_of_recipe(recipes, id_number, "family")

family <- ifelse(is.na(family), "", "{{< fa heart size=2xs >}}")
```

## `r title` `r vegan` `r freezes` `r family`

:::: {.columns}

::: {.column width="70%"}

```{r}
get_part_of_recipe(recipes, id_number, "ingredients") |>
  plain_list() 
```

:::

::: {.column width="10%"}

:::

::: {.column width="20%"}

```{r}
#| output: asis

get_detail(recipes, id_number, "temperature")
```

```{r}
#| output: asis

get_detail(recipes, id_number, "time")
```

```{r}
#| output: asis

get_detail(recipes, id_number, "size_and_quantity")
```

:::

::::

```{r}
#| output: asis

get_part(recipes, id_number, "method")
```

```{r}
#| output: asis

get_part(recipes, id_number, "notes")
```

```{r}
#| output: asis

link <- recipes |>
    dplyr::filter(id == id_number) |>
    dplyr::pull(link)
  
if(!is.na(link)){
  knitr::knit_child(input = "child-dir/_child-link.qmd",
                        envir = environment(),
                        quiet = TRUE) |>
  cat(sep = '\n')
}
```

```{r}
#| output: asis

pictures <- list.files(path = "pictures/", recursive = TRUE)

number_pictures <- sum(grepl(id_number, pictures))
  
numbers <- 1:number_pictures
numbers <- ifelse(nchar(numbers) < 2, paste0("0", numbers), numbers)
  
if(number_pictures == 1){
  knitr::knit_child(input = "child-dir/_child-one-picture.qmd",
                        envir = environment(),
                        quiet = TRUE) |>
  cat(sep = '\n')
} else if (number_pictures == 2){

  knitr::knit_child(input = "child-dir/_child-two-pictures.qmd",
                        envir = environment(),
                        quiet = TRUE) |>
  cat(sep = '\n')
} else if (number_pictures == 3){

  knitr::knit_child(input = "child-dir/_child-three-pictures.qmd",
                        envir = environment(),
                        quiet = TRUE) |>
  cat(sep = '\n')
}
```



